### ISSUE TITLE
ERR_INVALID_PACKAGE_TARGET

### ISSUE THREAD

**Issue by AntonLukichev** [slmgc/Nothing#8]
Hi,
the module v1.0.3 fail build

i have error 
`[15:41:23][Step 4/16] Error [ERR_INVALID_PACKAGE_TARGET]: Invalid "exports" main target "dist/nothing-mock.modern.js" defined in the package config /app/node_modules/nothing-mock/package.json
[15:41:23][Step 4/16]     at resolveExportsTarget (internal/modules/cjs/loader.js:574:13)
[15:41:23][Step 4/16]     at applyExports (internal/modules/cjs/loader.js:503:14)
[15:41:23][Step 4/16]     at resolveExports (internal/modules/cjs/loader.js:541:12)
[15:41:23][Step 4/16]     at Function.Module._findPath (internal/modules/cjs/loader.js:661:22)
[15:41:23][Step 4/16]     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:963:27)
[15:41:23][Step 4/16]     at Function.Module._load (internal/modules/cjs/loader.js:859:27)
[15:41:23][Step 4/16]     at Module.require (internal/modules/cjs/loader.js:1036:19)
[15:41:23][Step 4/16]     at require (internal/modules/cjs/helpers.js:72:18)
[15:41:23][Step 4/16]     at Object.vpgr (/app/.next/server/pages/404.js:9140:18)
[15:41:23][Step 4/16]     at __webpack_require__ (/app/.next/server/pages/404.js:23:31) {
[15:41:23][Step 4/16]   type: 'NodeError',
[15:41:23][Step 4/16]   code: 'ERR_INVALID_PACKAGE_TARGET'
[15:41:23][Step 4/16] }
[15:41:23][Step 4/16] npm ERR! code ELIFECYCLE
[15:41:23][Step 4/16] npm ERR! errno 1`

problem is in value "exports" in package.json
`"exports": "dist/nothing-mock.modern.js",`
in [documentation](https://nodejs.org/api/packages.html)  

> two fields can define entry points for a package: "main" and "exports"

Microbundle package says to use
> "esmodule": "dist/foo.modern.js", // Modern bundle

**Comment by slmgc** [comment]
@AntonLukichev hi, thanks for the info. I've used the fields from the microbundle's installation guide which contains both "main" and "exports" fields: https://github.com/developit/microbundle#-installation--setup--

```JS
{
  "name": "foo",                   // your package name
  "source": "src/foo.js",          // your source code
  "main": "dist/foo.js",           // where to generate the CommonJS/Node bundle
  "exports": "./dist/foo.modern.js", // path to the modern output (see below)
  "module": "dist/foo.module.js",  // where to generate the ESM bundle
  "unpkg": "dist/foo.umd.js",      // where to generate the UMD bundle (also aliased as "umd:main")
  "scripts": {
    "build": "microbundle",        // compiles "source" to "main"/"module"/"unpkg"
    "dev": "microbundle watch"     // re-build when source files change
  }
}
```
I'll update the package if this breaks the build for you.

**Comment by slmgc** [comment]
Updated `package.json`, please feel free to re-open the issue if it still fails for you.
